Initial code review 1
BelindaWilliams/BelindaWilliams.github.io pull request #1
Opened 2021-09-08 13:53 UTC by BelindaWilliams

2021-09-08 14:32 UTC, henridvf commented on index.html
> +	  <div class="project1">
Each project has its own style (project1, 2, 3 in CSS). Do you intend to differentiate between how you style each project?

2021-09-08 14:32 UTC, henridvf commented on CSS/Portfolio_mystyles.css
> +.project1, .project2, .project3 {
See comment below in main html file about using different styling for each project.

2021-09-09 09:02 UTC, tomgarrett95 requested changes
Great stuff - I could only spot one tiny error in your mystyles.css file!

2021-09-09 09:02 UTC, tomgarrett95 commented on CSS/mystyles.css
> +.dropbtn {
Blank line between rules.

2021-09-09 09:16 UTC, tomgarrett95 approved these changes

2021-09-09 09:17 UTC, merged